@echo off
cls
goto menu

:menu
cls
echo Select file:
set /p file=
cls
if exist %file% (
    goto unpack
) else (
    %file% doesn't exist.
    pause
    goto menu
)

:unpack
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
echo Unpacking...
ping localhost -n 1 >%file%.dll
cls
